Repository Theseus-Aegis/GTArmory, pull requests merged in 2020-02, with the labels that each got.

#4 Add Actions CI workflow (config check, HEMTT build)
  .github/workflows/arma.yml
  addons/ammunition/CfgAmmo.hpp
  addons/m1014/CfgWeapons.hpp
  addons/m1014/script_component.hpp
  addons/saiga12/script_component.hpp
  addons/scar/CfgWeapons.hpp
  addons/sg510/script_component.hpp
  hemtt.toml
Labels: tools

#6 Add PR and Issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement-request.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: tools

#9 Fix inheritance and final cleanup
  addons/ak/CfgWeapons.hpp
  addons/ak/config.cpp
  addons/ammunition/CfgAmmo.hpp
  addons/ammunition/CfgMagazineWells.hpp
  addons/ammunition/CfgMagazines.hpp
  addons/ammunition/config.cpp
  addons/glock/CfgWeapons.hpp
  addons/glock/config.cpp
  addons/l85/CfgWeapons.hpp
  addons/l85/config.cpp
  addons/m1014/CfgWeapons.hpp
  addons/m1014/config.cpp
  addons/main/CfgMods.hpp
  addons/main/config.cpp
  addons/main/stringtable.xml
  addons/main/ui/tacgt_logo_128.paa
  addons/main/ui/tacgt_logo_64.paa
  addons/mp5/CfgMagazineWells.hpp
  addons/mp5/CfgWeapons.hpp
  addons/mp5/config.cpp
  addons/mp7/CfgWeapons.hpp
  addons/mp7/config.cpp
  addons/saiga12/CfgWeapons.hpp
  addons/saiga12/config.cpp
  addons/scar/CfgRecoils.hpp
  addons/scar/CfgWeapons.hpp
  addons/scar/config.cpp
  addons/sg510/CfgWeapons.hpp
  addons/sg510/config.cpp
  hemtt.toml
Labels: bug fix, enhancement

#10 M1014 magwell error fix
  addons/m1014/CfgWeapons.hpp
  addons/saiga12/config.cpp
Labels: bug fix

#11 Version change
  addons/main/script_macros.hpp
  addons/main/script_version.hpp
Labels: enhancement

#12 Add Stringtables
  addons/ammunition/CfgAmmo.hpp
  addons/ammunition/CfgMagazines.hpp
  addons/ammunition/stringtable.xml
  addons/glock/CfgWeapons.hpp
  addons/glock/stringtable.xml
  addons/scar/CfgWeapons.hpp
  addons/scar/stringtable.xml
Labels: enhancement, translation

#13 Add PMAG/EMAG Magazines
  addons/ammunition/CfgAmmo.hpp
  addons/ammunition/CfgMagazineWells.hpp
  addons/ammunition/CfgMagazines.hpp
  addons/ammunition/config.cpp
  addons/ammunition/stringtable.xml
  addons/glock/CfgWeapons.hpp
  addons/glock/stringtable.xml
  addons/scar/CfgWeapons.hpp
  addons/scar/stringtable.xml
Labels: enhancement
