Repository Theseus-Aegis/GTArmory, pull requests merged in 2022-10, with the labels that each got.

#107 Ammunition - Add Handgun Ammo
  addons/ammunition/CfgAmmo.hpp
  addons/ammunition/CfgMagazineWells.hpp
  addons/ammunition/CfgMagazines.hpp
  addons/ammunition/CfgWeapons.hpp
  addons/ammunition/config.cpp
  addons/ammunition/handgun_magazines/357.hpp
  addons/ammunition/handgun_magazines/45ACP.hpp
  addons/ammunition/handgun_magazines/9x19.hpp
  addons/ammunition/magwells/handgun.hpp
  addons/ammunition/magwells/rifle.hpp
  addons/chiappa/CfgAmmo.hpp
  addons/chiappa/CfgMagazineWells.hpp
  addons/chiappa/config.cpp
Labels: feature request

#108 Special - Add Zaks Special Item
  addons/ammunition/CfgAmmo.hpp
  addons/ammunition/CfgMagazines.hpp
  addons/ammunition/handgun_magazines/10mm.hpp
  addons/special/CfgWeapons.hpp
  addons/special/config.cpp
Labels: feature request

#109 Ammunition/Remass - Move Remass into Ammunition
  addons/ammunition/magazines/762x39.hpp
  addons/ammunition/magazines/762x51.hpp
  addons/ammunition/magazines/762x54r.hpp
  addons/remass/$PBOPREFIX$
  addons/remass/BI.hpp
  addons/remass/CUP.hpp
  addons/remass/CfgMagazines.hpp
  addons/remass/NiArms.hpp
  addons/remass/README.md
  addons/remass/config.cpp
  addons/remass/script_component.hpp
Labels: enhancement

#110 Special - Update Texture and Name
  addons/ammunition/handgun_magazines/10mm.hpp
  addons/special/CfgWeapons.hpp
  addons/special/config.cpp
  addons/special/data/228slides_zz_co.paa
Labels: enhancement

#111 Add Resound Component
  addons/ak/$PBOPREFIX$
  addons/ak/CfgWeapons.hpp
  addons/ak/README.md
  addons/ak/config.cpp
  addons/ak/script_component.hpp
  addons/deagle/$PBOPREFIX$
  addons/deagle/CfgWeapons.hpp
  addons/deagle/README.md
  addons/deagle/config.cpp
  addons/deagle/script_component.hpp
  addons/l85/$PBOPREFIX$
  addons/l85/CfgWeapons.hpp
  addons/l85/README.md
  addons/l85/config.cpp
  addons/l85/script_component.hpp
  addons/m1014/$PBOPREFIX$
  addons/m1014/CfgWeapons.hpp
  addons/m1014/README.md
  addons/m1014/config.cpp
  addons/m1014/script_component.hpp
  addons/minigun/$PBOPREFIX$
  addons/minigun/CfgWeapons.hpp
  addons/minigun/README.md
  addons/minigun/config.cpp
  addons/minigun/script_component.hpp
  addons/mk6/$PBOPREFIX$
  addons/mk6/README.md
  addons/mk6/config.cpp
  addons/mk6/script_component.hpp
  addons/mp7/$PBOPREFIX$
  addons/mp7/CfgWeapons.hpp
  addons/mp7/README.md
  addons/mp7/script_component.hpp
  addons/resound/$PBOPREFIX$
  addons/resound/CfgAmmo.hpp
  addons/resound/CfgWeapons.hpp
  addons/resound/README.md
  addons/resound/config.cpp
  addons/resound/script_component.hpp
  addons/resound/weapons/ak.hpp
  addons/resound/weapons/deagle.hpp
  addons/resound/weapons/l85.hpp
  addons/resound/weapons/m1014.hpp
  addons/resound/weapons/minigun.hpp
  addons/resound/weapons/mp7.hpp
  addons/resound/weapons/saiga12k.hpp
  addons/saiga12/$PBOPREFIX$
  addons/saiga12/CfgWeapons.hpp
  addons/saiga12/README.md
  addons/saiga12/config.cpp
  addons/saiga12/script_component.hpp
Labels: enhancement

#112 Add Spare Barrel Component
  addons/sparebarrel/$PBOPREFIX$
  addons/sparebarrel/CfgWeapons.hpp
  addons/sparebarrel/README.md
  addons/sparebarrel/config.cpp
  addons/sparebarrel/script_component.hpp
Labels: feature request

#114 Special - Extend Tattoo & rename file.
  addons/special/CfgFaces.hpp
  addons/special/data/mikemf_face_co.paa
  addons/special/data/tyronemf_face_co.paa
Labels: enhancement

#113 Add Markers Component
  addons/markers/$PBOPREFIX$
  addons/markers/CfgMarkerClasses.hpp
  addons/markers/CfgMarkers.hpp
  addons/markers/config.cpp
  addons/markers/data/actual.paa
  addons/markers/data/ares1.paa
  addons/markers/data/ares2.paa
  addons/markers/data/ares3.paa
  addons/markers/data/ares4.paa
  addons/markers/data/helios.paa
  addons/markers/data/landingzone.paa
  addons/markers/data/nemesis.paa
  addons/markers/data/rallypoint.paa
  addons/markers/data/vrp.paa
  addons/markers/data/waypoint.paa
  addons/markers/script_component.hpp
Labels: feature request

#117 Ammunition - Penetration fixes
  addons/ammunition/CfgAmmo.hpp
  addons/ammunition/magazines/57x28.hpp
Labels: bug fix

#118 Add Entrenching Component
  addons/entrenching/$PBOPREFIX$
  addons/entrenching/CfgVehicles.hpp
  addons/entrenching/README.md
  addons/entrenching/config.cpp
  addons/entrenching/script_component.hpp
Labels: feature request

#123 Ammunition - New PMAG model without QP
  addons/ammunition/magazines/556x45.hpp
  addons/ammunition/script_component.hpp
Labels: feature request

#125 Add Training Component
  addons/training/$PBOPREFIX$
  addons/training/CfgAmmo.hpp
  addons/training/CfgMagazines.hpp
  addons/training/CfgVehicles.hpp
  addons/training/CfgWeapons.hpp
  addons/training/README.md
  addons/training/config.cpp
  addons/training/script_component.hpp
Labels: feature request

#124 Recoils - Add Western Sahara weapons
  addons/recoils/CfgWeapons.hpp
  addons/recoils/baseclasses.hpp
  addons/recoils/ws/12G/aa40.hpp
  addons/recoils/ws/556/velko.hpp
  addons/recoils/ws/556/xms.hpp
  addons/recoils/ws/762R/galat.hpp
Labels: enhancement

#128 Ammunition - Add magazine tags
  addons/ammunition/magazines/12g.hpp
  addons/ammunition/magazines/300Blackout.hpp
  addons/ammunition/magazines/45ACP.hpp
  addons/ammunition/magazines/46x30.hpp
  addons/ammunition/magazines/545x39.hpp
  addons/ammunition/magazines/556x45.hpp
  addons/ammunition/magazines/57x28.hpp
  addons/ammunition/magazines/58x42.hpp
  addons/ammunition/magazines/65x39.hpp
  addons/ammunition/magazines/68x43.hpp
  addons/ammunition/magazines/762x39.hpp
  addons/ammunition/magazines/762x51.hpp
  addons/ammunition/magazines/762x54r.hpp
  addons/ammunition/magazines/9x19.hpp
  addons/ammunition/magazines/9x39.hpp
Labels: enhancement
