Repository Theseus-Aegis/GTArmory, pull requests merged in 2023-04, with the labels that each got.

#144 Supplies - Add 10x Toolkit to Engineer supplies
  addons/supplies/CfgVehicles.hpp
Labels: enhancement

#148 Adapt to HEMTT v1
  .github/workflows/arma.yml
  .gitignore
  .hemtt/hooks/post_release/01_notes.rhai
  .hemtt/project.toml
  addons/ammunition/magwells/rifle.hpp
  addons/flashlight/ANPEQ_Top_Tan.hpp
  addons/main/script_macros.hpp
  addons/main/script_mod.hpp
  addons/rpg/CfgAmmo.hpp
  build.bat
  hemtt.toml
  make_release.bat
  tools/setup.bat
Labels: tools

#146 Supplies - Add Theseus Fuel Canister
  addons/supplies/CfgVehicles.hpp
  addons/supplies/data/canisterfuel_theseus.paa
  addons/supplies/ui/supplies_FuelCanister.jpg
Labels: feature request

#147 Headgear - Add Cap w/DEF (New York Mets)
  addons/headgear/$PBOPREFIX$
  addons/headgear/CfgWeapons.hpp
  addons/headgear/README.md
  addons/headgear/config.cpp
  addons/headgear/data/cap_def_nymets_co.paa
  addons/headgear/data/cup_opscore_medic_1_co.paa
  addons/headgear/data/cup_opscore_medic_2_co.paa
  addons/headgear/data/cup_opscore_medic_co.paa
  addons/headgear/script_component.hpp
  addons/helmet/$PBOPREFIX$
  addons/helmet/README.md
Labels: feature request

#149 Special - Update Joram's helmet texture
  addons/special/data/joram_helipilot_black_co.paa
Labels: enhancement
